const recipes = [
  {
    id: recipe1,
    title: ["Chilli", "Bowl"],
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe2,
    title: ["Caesar", "Bowl"],
    image: "image/lunchpic13.png",
    ingredients: [
      "2 cups Romaine lettuce",
      "½ cup Croutons (about a small handful)",
      "2 tablespoons Parmesan cheese",
      "4 to 6 Cherry tomatoes",
      "2 tablespoons Caesar dressing",
      "1 small Grilled chicken breast breast",
    ],
    descriptiontitle: ["Caesar bowls are a straight-up classic."],
    description: [
      "They’re crunchy, creamy, and packed with flavor—from the crisp romaine to the tangy dressing and golden croutons. Toss in some parmesan and juicy tomatoes, and boom—you’ve got a simple salad that hits way harder than it should. Want it more filling? Just add chicken or chickpeas and you’ve got yourself a full-on power lunch. Iconic taste, zero fuss.",
    ],
    steps1: [
      "1. Wash and chop about 2 cups of romaine lettuce. Pat dry so it stays nice and crisp.",
      "2. If using fresh bread, cube it up and toss with a little olive oil, salt, and garlic powder. Bake or pan-toast until golden and crunchy. Or just grab your fave store-bought ones.",
      "3. Cut 4–6 cherry tomatoes in half for a pop of sweetness and color.",
      "4. In a big bowl, toss the lettuce with 2 tablespoons of Caesar dressing until everything’s lightly coated.",
    ],
    steps2: [
      "5. Add the croutons, shaved parmesan (about 2 tablespoons), and those cherry tomatoes.",
      "Optional extras: Want more protein? Add some grilled chicken, crispy chickpeas, or even a boiled egg. Feeling fancy? A little squeeze of lemon and cracked black pepper never hurt.",
      "Serve it up: Grab a fork, dive in, and enjoy your crunchy, creamy, dreamy Caesar bowl.",
    ],
  },
  {
    id: recipe3,
    title: ["Halloumi", "Bowl"],
    image: "image/lunchpic12.png",
    ingredients: [
      "100g Halloumi cheese",
      "2 cups Mixed greens",
      "4–6 Cherry tomatoes",
      "A few thin slices of Red onion",
      "1 tsp Olive oil",
      "Fresh herbs, parsley or mint",
      "1–2 tbsp Dressing",
    ],
    descriptiontitle: ["Halloumi Bowls are a vibe."],
    description: [
      "Crispy on the outside, gooey in the middle—halloumi is the kind of cheese that just shows off. This bowl is a flavor bomb, with grilled halloumi taking center stage over a bed of fresh greens, juicy cherry tomatoes, and crunchy extras. It’s got protein, texture, and serious Mediterranean energy. Serve it warm and watch it disappear. Peak salad goals.",
    ],
    steps1: [
      "1. Rinse and dry your greens. Slice the cherry tomatoes and onion.",
      "2. Heat a non-stick pan over medium heat. Add a little olive oil and grill the halloumi slices (sliced into ~½-inch thick pieces) for about 2 minutes per side, until golden brown and crispy on the outside.",
      "3. Lay down the greens (baby spinach, arugula, frisée, etc.), scatter the cherry tomatoes and red onion, then top with the grilled halloumi.",
    ],
    steps2: [
      "4. Add your dressing of choice (balsamic glaze, lemon-tahini, or olive oil + lemon juice work great) and finish with chopped herbs if you're feeling extra.",
      "5. (Serve immediately) This one's best while the halloumi is still warm and slightly melty inside.",
    ],
  },
  {
    id: recipe4,
    title: ["Lentil", "Stew"],
    image: "image/lunchpic3.png",
    ingredients: [
      "¾ cup Cooked lentils",
      "½ medium Potato",
      "1 small Carrot",
      "¼ medium Onion",
      "½ cup Crushed tomatoes",
      "1 clove Garlic",
      "1 tsp Olive oil",
      "½ tsp each Paprika & cumin",
      "About 1 cup Veggie broth or water",
    ],
    descriptiontitle: ["Lentil Stew is comfort in a bowl"],
    description: [
      "It’s warm, filling, and packed with plant-based goodness. With earthy lentils, chunky veggies, and a rich tomato-spiced broth, this stew is your go-to for cozy days, meal prep wins, or when you just want something that hits like a hug. It’s hearty, nourishing, and totally satisfying—no frills, just flavor.",
    ],
    steps1: [
      "1. Sauté the aromatics: Heat olive oil in a pot over medium heat. Add finely chopped onion and minced garlic, sauté until soft and fragrant (about 2–3 minutes).",
      "2. Add veggies & spices: Toss in the diced carrot and potato. Sprinkle in paprika, cumin, salt, and pepper (to taste). Stir and let cook for a few minutes.",
      "3. Add liquids & lentils: Pour in the crushed tomatoes and veggie broth (adjust as needed). Stir in the lentils (brown or green work great). Bring to a boil, then lower to a simmer.",
    ],
    steps2: [
      "5. Simmer until tender: Let it cook for 15–20 minutes, or until potatoes and carrots are fork-tender. Add more broth if it gets too thick.",
      "6. Stir in greens (optional): Toss in a handful of spinach or kale at the end and let it wilt.",
      "7. Serve it up: Pour into a bowl, top with parsley (optional), and add a scoop of barley or rice if you’re feeling it",
    ],
  },
  {
    id: recipe5,
    title: "Carbonara",
    image: "image/lunchpic4.png",
    ingredients: [
      "75g Spaghetti",
      "50g Pancetta or bacon",
      "1 large Egg",
      "¼ cup Parmesan or Pecorino",
      "1 clove Garlic",
      "Salt & Pepper (to taste)",
    ],
    descriptiontitle: ["Carbonara is the cheat code to comfort"],
    description: [
      "It’s creamy (without cream), smoky, salty, and ridiculously satisfying—all made in one pan, in under 20 minutes. With just a few pantry staples and zero fluff, carbonara proves that simple really can be spectacular. Fork-twirling bliss? Confirmed.",
    ],
    steps1: [
      "1. Cook the pasta: Boil spaghetti in salted water until al dente. Reserve a bit of pasta water before draining. (About 2–3)",
      "2. Crisp the bacon: While pasta cooks, fry the diced pancetta or bacon in a skillet over medium heat until crispy. Add the smashed garlic (optional) for a quick sizzle if using, then remove it.",
      "3. Make the sauce base: In a bowl, whisk together the egg, grated cheese, and lots of black pepper.",
    ],
    steps2: [
      "4. Combine off heat: Once the pasta is cooked and drained, immediately toss it into the pan with the bacon (off the heat). Quickly stir in the egg-cheese mix, adding a splash of hot pasta water to create a silky sauce.",
      "5. Stir until creamy: Keep tossing until everything is glossy and coated. The heat from the pasta cooks the egg gently, turning it into a dreamy sauce.",
      "6. Serve hot: Top with extra cheese and black pepper. Eat immediately and smile.",
    ],
  },
  {
    id: recipe6,
    title: ["Tomato", "Pasta"],
    image: "image/lunchpic12.png",
    ingredients: [
      "75–100g Pasta",
      "1 clove Garlic",
      "½ cup Canned crushed tomatoes or passata",
      "1 tbsp Olive oil",
      "Salt & pepper to taste",
      "A pinch of Chili flakes (optional)",
    ],
    descriptiontitle: ["Tomato Pasta is the OG weeknight hero"],
    description: [
      "It’s simple, saucy, and totally unfussy—but still manages to taste like you put in way more effort than you did. With just a handful of ingredients and one pot, it brings that cozy, classic Italian comfort without the fuss. Fast, flavorful, and always reliable.",
    ],
    steps1: [
      "1. Cook the pasta (spaghetti, penne, fusilli—whatever you love): Boil in salted water until al dente. Reserve 2–3 tablespoons of the pasta water before draining.",
      "2. Make the sauce: While pasta cooks, heat olive oil in a pan over medium heat. Add minced garlic (and chili flakes if using), and sauté for about 30 seconds — don’t let it burn.",
      "3. Add the tomatoes: Pour in the crushed tomatoes or passata. Stir, season with salt and pepper, and let it simmer for 5–10 minutes to thicken slightly.",
    ],
    steps2: [
      "4. Combine & finish: Add the drained pasta to the sauce, along with a splash of pasta water. Toss everything together until the sauce coats the pasta beautifully.",
      "5. Serve & top it off: Plate it up, sprinkle with cheese and fresh herbs (Fresh basil or parsley) if you’ve got ‘em, and enjoy!",
    ],
  },
  {
    id: recipe7,
    title: ["Tomato", "Soup"],
    image: "image/lunchpic6.png",
    ingredients: [
      "1 cup Canned crushed tomatoes or passata",
      "¼ small Onion",
      "1 clove Garlic",
      "1 tbsp Butter or olive oil",
      "½ cup Vegetable broth or water",
      "1 tbsp Cream or milk (optional)",
      "½ tsp Sugar",
    ],
    descriptiontitle: ["Tomato Soup is a cozy hug in a mug"],
    description: [
      "It’s smooth, savory, and endlessly comforting. Whether you're under the weather, short on time, or just craving something warm and nostalgic—this quick tomato soup delivers. Minimal ingredients, maximum comfort. Bonus points if you pair it with a grilled cheese.",
    ],
    steps1: [
      "1. Sauté aromatics: In a small saucepan, melt butter or heat olive oil over medium heat. Add finely chopped onion and minced garlic, and sauté until soft and fragrant—about 2–3 minutes.",
      "2. Add tomatoes & broth: Pour in the crushed tomatoes and broth(adjust for preferred thickness). Stir in salt, pepper, herbs, and a pinch of sugar (for balancing acidity)",
      "3. Simmer: Let the soup bubble gently for about 10–12 minutes, stirring occasionally, until flavors meld and it thickens a bit.",
    ],
    steps2: [
      "4. Blend (optional): For a smooth texture, blend with an immersion blender (or transfer carefully to a regular blender).",
      "5. Cream it (optional): Stir in a splash of cream or milk for extra richness.",
      "6. Serve hot: Top with a swirl of cream, fresh herbs, or a crack of black pepper. Bonus: dunk a grilled cheese or croutons in there.",
    ],
  },
  {
    id: recipe8,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe1,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe1,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe1,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe1,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe1,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe1,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe1,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe1,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe1,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe1,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe1,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe1,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe1,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe1,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe1,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
  {
    id: recipe1,
    title: "Chilli Bowl",
    image: "image/lunchpic1.png",
    ingredients: [
      "1 Avocado",
      "100g white rice",
      "1 raw salmon",
      "1 cup seaweed salad",
      "1 cup cucumber slices",
      "Sesame seeds",
    ],
    descriptiontitle: ["Salmon bowls are the real MVP"],
    description: [
      "They’re packed with protein, omega-3s (hello, brain boost), and all the good fats that keep your skin glowing. Plus, they’re usually loaded with veggies and rice or quinoa, so it’s like a full-on balanced meal that actually slaps. Tasty and good for you? Big win.",
    ],
    steps1: [
      "This fresh and vibrant salmon poke bowl starts with a base of perfectly seasoned sushi rice:",
      "1. Begin by rinsing 1 cup of sushi rice until the water runs clear, then cook according to package instructions. ",
      "2. Once cooked, season it with a mix of rice vinegar, sugar, and salt, and let it cool. ",
      "3. While the rice is cooling, dice sushi-grade salmon into small cubes and marinate it in soy sauce and sesame oil, with optional sriracha for heat. Let the salmon chill in the fridge for 10–15 minutes. ",
      "4. Meanwhile, slice fresh cucumber into thin rounds, dice a ripe avocado, and prepare a scoop of store-bought seaweed salad. You can also sprinkle a little lemon on the avocado to keep it fresh.",
    ],
    steps2: [
      "5. To assemble the bowl, start with a layer of rice, then arrange the marinated salmon, cucumber slices, avocado chunks, and seaweed salad neatly around it. ",
      "6. Finish with a sprinkle of black sesame seeds for that extra pop. Optional toppings like spicy mayo, edamame, or pickled ginger can add extra flavor and flair. ",
      "7. Chill the serving bowl beforehand for max freshness. The result? A balanced, nourishing, and photogenic bowl packed with protein, healthy fats, and crunch — ideal for a quick lunch or light dinner that feels like a treat.",
    ],
  },
];
